spring:
  application:
    name: WarehouseQrApplication
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocol: TLSv1.2
            trust: smtp.gmail.com
          debug: true
  web:
    resources:
      static-locations: classpath:/static/ # Современное свойство для статического контента
  main:
    allow-bean-definition-overriding: true
app:
  base-url: /
  qrcode-base-url: /api/qrcodes/
  reservation-base-url: /api/reservation/

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from DigitalOcean!

jwt:
  secret: ${JWT_SECRET}